/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
      extend: {
        colors: {
          "on-secondary-fixed": "#150066",
          "inverse-surface": "#2d3133",
          "on-background": "#181c1e",
          "surface-container-lowest": "#ffffff",
          "surface-container-highest": "#e0e3e6",
          "primary": "#3056b5",
          "on-secondary-container": "#2f1f8f",
          "error-container": "#ffdad6",
          "background": "#f7fafd",
          "surface-container-high": "#e5e8eb",
          "on-secondary": "#ffffff",
          "on-primary-container": "#fefcff",
          "on-error": "#ffffff",
          "on-primary": "#ffffff",
          "on-tertiary-container": "#fffbff",
          "secondary-fixed": "#e4dfff",
          "on-tertiary-fixed": "#2c1700",
          "secondary-fixed-dim": "#c6c0ff",
          "primary-fixed": "#dbe1ff",
          "surface": "#f7fafd",
          "secondary-container": "#9a90ff",
          "on-tertiary": "#ffffff",
          "error": "#ba1a1a",
          "secondary": "#594fba",
          "surface-bright": "#f7fafd",
          "outline": "#747684",
          "surface-container": "#ebeef1",
          "inverse-primary": "#b3c5ff",
          "outline-variant": "#c4c6d4",
          "on-surface": "#181c1e",
          "on-error-container": "#93000a",
          "tertiary-container": "#a76500",
          "tertiary": "#855000",
          "surface-dim": "#d7dadd",
          "on-surface-variant": "#434652",
          "tertiary-fixed": "#ffdcbb",
          "inverse-on-surface": "#eef1f4",
          "on-primary-fixed": "#00174a",
          "primary-container": "#4c70cf",
          "on-secondary-fixed-variant": "#4135a1",
          "surface-variant": "#e0e3e6",
          "tertiary-fixed-dim": "#ffb869",
          "on-primary-fixed-variant": "#12409e",
          "surface-tint": "#3359b7",
          "surface-container-low": "#f1f4f7",
          "on-tertiary-fixed-variant": "#673d00",
          "primary-fixed-dim": "#b3c5ff",
          "brandBlue": "#5376D6",
          "brandPurple": "#6359C5",
          "bgGray": "#F3F6F9"
        },
        fontFamily: {
          "headline": ["Inter"],
          "body": ["Inter"],
          "label": ["Inter"]
        },
        borderRadius: {
          "DEFAULT": "0.25rem", 
          "lg": "0.5rem", 
          "xl": "0.75rem", 
          "full": "9999px",
          "custom-card": "1rem",
          "custom-btn": "0.5rem"
        },
      },
    },
    plugins: [
      require('@tailwindcss/forms'),
      require('@tailwindcss/container-queries')
    ],
}
